trivia-gt/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using System.Diagnostics;
using trivia_gt.DAL;
using trivia_gt.Models;

namespace trivia_gt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Correo") == null)
            {
                return Redirect("/Login/Login");
            }

            ViewBag.Nombres = HttpContext.Session.GetString("Nombres");
            ViewBag.Imagen = @"https://drive.google.com/uc?export=view&id=" + HttpContext.Session.GetString("Imagen");

            int dias = (int)HttpContext.Session.GetInt32("DiasConexion");

            if (dias > 1)
            {
                ViewBag.ImagenAnimo = @"https://drive.google.com/uc?export=view&id=1wQ3L1xIfvyfoUueYKik5GTNTM1tYU89w";
            } else
            {
                ViewBag.ImagenAnimo = @"https://drive.google.com/uc?export=view&id=1nocxQPDztHwLvbbacQcPUhmC2OmbTegL";
            }

            ViewBag.ImagenLibro = @"https://drive.google.com/uc?export=view&id=1JC2aNjxTR3he5mywYJY_lnCwG0duZUpp";
            
            ViewBag.Fecha = HttpContext.Session.GetString("FechaConexion");

            ViewBag.Visible = false;
            ViewBag.Nivel = 0;
            ViewBag.Percentage = 0;
            
            if (HttpContext.Session.GetString("mensaje") == null)
            {
                ViewBag.Mensaje = null;
            } else
            {
                ViewBag.Mensaje = HttpContext.Session.GetString("mensaje");
            }

            if (HttpContext.Session.GetString("informacion") == null)
            {
                ViewBag.Info = null;
            }
            else
            {
                ViewBag.Info = HttpContext.Session.GetString("informacion");
                HttpContext.Session.Remove("informacion");
            }

            ViewBag.IdRol = HttpContext.Session.GetInt32("IdRol");

            if (HttpContext.Session.GetInt32("idRol").Equals(1))
            {
                return View();

            } else
            {

                UsuarioDAL usuarioDAL = new();
                List<UsuarioBE> listaUsuario = usuarioDAL.Listar(new UsuarioBE());

                PunteoBE punteoBE = new();

                PunteoDAL punteoDAL = new();
                List<PunteoBE> listaPunteo = punteoDAL.Listar(new PunteoBE());

                string correo = HttpContext.Session.GetString("Correo");

                UsuarioBE usuario = listaUsuario.First(c => c.Correo.Equals(correo));

                listaUsuario.Remove(usuario);

                foreach (UsuarioBE usuarioBE in listaUsuario)
                {
                    if (listaPunteo.Exists(p => p.Correo.Equals(usuarioBE.Correo)))
                    {
                        usuarioBE.punteoBE = new();
                        usuarioBE.punteoBE = listaPunteo.First(p => p.Correo.Equals(usuarioBE.Correo));

                        switch (int.Parse(usuarioBE.punteoBE.Punteo) switch
                        {
                            5 or 10 => 1,
                            15 or 20 => 2,
                            25 or 30 => 3,
                            35 or 40 or 45 => 4,
                            50 => 5,
                            _ => 0,
                        })
                        {
                            case 1:
                                usuarioBE.punteoBE.estrella1 = 1;
                                usuarioBE.Orden = 1;
                                break;
                            case 2:
                                usuarioBE.punteoBE.estrella1 = 1;
                                usuarioBE.punteoBE.estrella2 = 1;
                                usuarioBE.Orden = 2;
                                break;
                            case 3:
                                usuarioBE.punteoBE.estrella1 = 1;
                                usuarioBE.punteoBE.estrella2 = 1;
                                usuarioBE.punteoBE.estrella3 = 1;
                                usuarioBE.Orden = 3;
                                break;
                            case 4:
                                usuarioBE.punteoBE.estrella1 = 1;
                                usuarioBE.punteoBE.estrella2 = 1;
                                usuarioBE.punteoBE.estrella3 = 1;
                                usuarioBE.punteoBE.estrella4 = 1;
                                usuarioBE.Orden = 4;
                                break;
                            case 5:
                                usuarioBE.punteoBE.estrella1 = 1;
                                usuarioBE.punteoBE.estrella2 = 1;
                                usuarioBE.punteoBE.estrella3 = 1;
                                usuarioBE.punteoBE.estrella4 = 1;
                                usuarioBE.punteoBE.estrella5 = 1;
                                usuarioBE.Orden = 5;
                                break;
                            default:
                                break;
                        }

                    } else
                    {
                        usuarioBE.punteoBE = new();
                        usuarioBE.punteoBE.Punteo = "0";
                    }

                    usuarioBE.Roles = new List<SelectListItem>();
                    usuarioBE.Roles.Add(new SelectListItem { Value = "1", Text = "Jugador" });
                    usuarioBE.Roles.Add(new SelectListItem { Value = "2", Text = "Administrador" });
                }

                return View(listaUsuario.OrderByDescending(o => o.Orden).ToList());
            }

        }


        [HttpPost]
        [Produces("application/json")]
        public IActionResult Actualiza([FromBody] UsuariosBE usuarios)
        {

            UsuarioDAL usuarioDAL = new();
           

            UsuarioBE usuarioBE = new UsuarioBE
            {
                Correo = usuarios.Correo,
                IdRol = usuarios.IdRol,
                IsEditing = true
            };

            usuarioDAL.Actualizar(usuarioBE);

            return Json(new { success = true, direccion = "/Home/Index" }, new Newtonsoft.Json.JsonSerializerSettings());
        }

        [HttpPost]
        [Produces("application/json")]
        public IActionResult Grabar([FromBody] List<UsuariosBE> usuarios)
        {
            UsuarioDAL usuarioDAL = new();

            foreach (UsuariosBE item in usuarios)
            {
                UsuarioBE usuarioBE = new UsuarioBE
                {
                    Correo = item.Correo,
                    IdRol = item.IdRol,
                    IsEditing = true
                };

                usuarioDAL.Actualizar(usuarioBE);
            }

            return Json(new { success = true, direccion = "/Home/Index" }, new Newtonsoft.Json.JsonSerializerSettings());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Construccion()
        {
            if (HttpContext.Session.GetString("Correo") == null)
            {
                return Redirect("/Login/Login");
            }

            ViewBag.Nombres = HttpContext.Session.GetString("Nombres");
            ViewBag.Imagen = @"https://drive.google.com/uc?export=view&id=" + HttpContext.Session.GetString("Imagen");

            ViewBag.Visible = false;
            ViewBag.Nivel = 0;
            ViewBag.Percentage = 0;
            ViewBag.Mensaje = null;
            ViewBag.Info = null;
            ViewBag.IdRol = HttpContext.Session.GetInt32("IdRol");

            return View();
        }

    }
}

trivia-gt/Controllers/PreguntasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using trivia_gt.DAL;
using trivia_gt.Models;

namespace trivia_gt.Controllers
{
    public class PreguntasController : Controller
    {
        // GET: PreguntasController
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Correo") == null)
            {
                return Redirect("/Login/Login");
            }

            ViewBag.Nombres = HttpContext.Session.GetString("Nombres");
            ViewBag.Imagen = @"https://drive.google.com/uc?export=view&id=" + HttpContext.Session.GetString("Imagen");
            ViewBag.ImagenLibro = @"https://drive.google.com/uc?export=view&id=1JC2aNjxTR3he5mywYJY_lnCwG0duZUpp";
            ViewBag.IdRol = HttpContext.Session.GetInt32("IdRol");

            Int32 dias = (int)HttpContext.Session.GetInt32("DiasConexion");

            if (dias > 1)
            {
                ViewBag.ImagenAnimo = @"https://drive.google.com/uc?export=view&id=1wQ3L1xIfvyfoUueYKik5GTNTM1tYU89w";
            }
            else
            {
                ViewBag.ImagenAnimo = @"https://drive.google.com/uc?export=view&id=1nocxQPDztHwLvbbacQcPUhmC2OmbTegL";
            }

            ViewBag.Fecha = HttpContext.Session.GetString("FechaConexion");
            ViewBag.Visible = true;

            List<PreguntaBE>? lista = Utilities.ObtienePreguntasCache<List<PreguntaBE>>(HttpContext.Session);

            if (lista == null)
            {
                int idUsuario = (int)HttpContext.Session.GetInt32("IdUsuario");

                lista = Utilities.ListarPreguntas(HttpContext.Session, idUsuario);

                Utilities.GrabaPreguntasCache(HttpContext.Session, lista);
            }

            bool existe = lista.Exists(p => !p.respondio);
            
            if (!existe)
            {
                HttpContext.Session.SetString("mensaje", "Niveles Completados");
                return Redirect("/Home/Index");
            }

            PreguntaBE pregunta = lista.First(p => !p.respondio);

            ViewBag.Nivel = pregunta.nivel;

            //calcula el porcentaje

            existe = lista.Exists(p => p.respondio && p.nivel.Equals(pregunta.nivel));

            if (!existe)
            {
                ViewBag.Percentage = 0;
            } else
            {
                int contador = (lista.Where(p => p.respondio && p.nivel.Equals(pregunta.nivel)).ToList().Count * 100) / 5;
                ViewBag.Percentage = contador;
            }

            return View(pregunta);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Grabar(PreguntaBE entidad)
        {
            PreguntaDAL preguntaDAL = new PreguntaDAL();

            bool esCorrecta = false;

            if (entidad.idRespuesta == 0)
            {
                return Json(new { success = esCorrecta, message = MensajeError("Se debe seleccionar una pregunta"), direccion = string.Empty }, new Newtonsoft.Json.JsonSerializerSettings());
            }

            List<PreguntaBE>? lista = Utilities.ObtienePreguntasCache<List<PreguntaBE>>(HttpContext.Session);

            //optiene la pregunta
            PreguntaBE? pregunta = lista.First(p => p.idPregunta.Equals(entidad.idPregunta));

            //valida respuesta
            RespuestaBE respuesta = pregunta.respuestas.First(r => r.idRespuesta.Equals(entidad.idRespuesta));

            if (respuesta.is_correct == 1)
            {
                esCorrecta = true;
            }
            else
            {
                HttpContext.Session.Remove("preguntas");

                string actualiza;

                if (pregunta.idPunteo.Equals(0))
                {
                    //agrega la pregunta que se respondio de forma incorrecta;

                    int idUsuario = (int)HttpContext.Session.GetInt32("IdUsuario");

                    pregunta = new PreguntaBE();

                    pregunta.punteo = 0;
                    pregunta.intentos = 1;
                    pregunta.nivel = entidad.idPregunta <= 5 ? 1 : 2;
                    pregunta.idUsuario = idUsuario;
                    pregunta.idPregunta = entidad.idPregunta;
                    pregunta.idEstado = 2;

                    _ = preguntaDAL.Crear(pregunta);

                } else
                {
                    pregunta.intentos++;
                    pregunta.punteo = 0;
                    pregunta.idEstado = 2;

                    _ = preguntaDAL.Actualizar(pregunta);
                }
                
                return Json(new { success = esCorrecta, message = MensajeError("Respuesta incorrecta!!! Clic para continual"), direccion = "/Preguntas/Index" }, new Newtonsoft.Json.JsonSerializerSettings());
            }

            int indexList = lista.IndexOf(pregunta);

            lista.Remove(pregunta);

            pregunta.idRespuesta = entidad.idRespuesta;
            pregunta.respondio = true;
            pregunta.idUsuario = (int)HttpContext.Session.GetInt32("IdUsuario");
            pregunta.punteo = 5;
            pregunta.intentos++;
            pregunta.idEstado = 1;

            lista.Insert(indexList, pregunta);

            if (pregunta.idPunteo.Equals(0))
            {
                _ = preguntaDAL.Crear(pregunta);
            }
            else
            {
                _ = preguntaDAL.Actualizar(pregunta);
            }
            
            Utilities.GrabaPreguntasCache(HttpContext.Session, lista);

            return Json(new { success = esCorrecta, message = Mensaje(), direccion = "/Preguntas/Index" }, new Newtonsoft.Json.JsonSerializerSettings());

        }

        private string Mensaje()
        {
            StringBuilder html = new(string.Empty);

            html.Append("<div class='card align-content-center text-center' style='background-color:#32C682'>");
            html.Append(" <img class='w-25 h-auto rounded card-img-top mx-auto d-block' src='https://drive.google.com/uc?export=view&id=1nocxQPDztHwLvbbacQcPUhmC2OmbTegL'>");
            html.Append("<div class='card-body'>");
            html.Append("<p class='card-text text-white font-weight-bold fs-5'>Respuesta correcta!!! clic para continuar</p>");
            html.Append("</div></div>");

            return html.ToString();
        }

        private string MensajeError(string mensaje)
        {
            StringBuilder html = new(string.Empty);

            html.Append("<div class='card align-content-center text-center' style='background-color:#FA5549'>");
            html.Append(" <img class='w-25 h-auto rounded card-img-top mx-auto d-block' src='https://drive.google.com/uc?export=view&id=1wQ3L1xIfvyfoUueYKik5GTNTM1tYU89w'>");
            html.Append("<div class='card-body'>");
            html.Append("<p class='card-text text-white font-weight-bold fs-5'>" + mensaje + "</p>");
            html.Append("</div></div>");

            return html.ToString();
        }

    }
}

trivia-gt/Views/Home/Construccion.cshtml
<div class="container d-flex h-100 mt-2">
    <div class="row justify-content-center align-items-center">
        <div class="card">
            <img class="w-25 h-auto rounded mx-auto" src="~/images/construccion.jpg">
            <div class="card-body">
                <a class="btn btn-primary" href="@Url.Action("Index", "Home")">Regresar</a>
            </div>
        </div>
    </div>
</div>

trivia-gt/Views/Home/Index.cshtml
@model IEnumerable<trivia_gt.Models.UsuarioBE>

@{
    ViewData["Title"] = "Menu";
    string imageLibro = ViewBag.ImagenLibro;
    string imageAnimo = ViewBag.ImagenAnimo;
    string fecha = ViewBag.Fecha;
    int IdRol = ViewBag.IdRol;

}

<div class="text-center">

    @if (IdRol.Equals(1))
    {
        <div class="card-group mt-5">
            <div class="card float-start">

                <figure class="figure">
                    <div class="card-img-top">
                        <img src="@imageAnimo" class="w-25 figure-img img-fluid rounded">
                    </div>
                    <div class="card-body">
                        <figcaption class="figure-caption text-success" style=" font-size:large!important">El último día que jugaste fue el @fecha</figcaption>
                    </div>
                </figure>

            </div>
            <div class="card float-end">

                <figure class="figure">
                    <div class="card-img-top">
                        <img src="@imageLibro" class="w-25 figure-img img-fluid rounded">
                    </div>
                    <div class="card-body">
                        <figcaption class="figure-caption" style="font-size:large!important">
                            @if (IdRol == 1)
                            {
                                <a class="btn btn-lg btn-success fs-1" href="@Url.Action("Index", "Preguntas")">
                                    <span class="fs-1"><i class="fa fa-play-circle me-2"></i></span>Jugar
                                </a>
                            }
                            else
                            {
                                <a class="btn btn-lg btn-success fs-1" href="#">
                                    <span class="fs-1"><i class="fa fa-play-circle me-2"></i></span>Jugar
                                </a>
                            }

                        </figcaption>
                    </div>
                </figure>

            </div>
        </div>
    }
    else
    {
        @using (Html.BeginForm("Grabar", "Home", FormMethod.Post, new { @class = "form-horizontal bg-light", Id = "frmTablaUsuarios", role = "form" }))
        {
            @Html.AntiForgeryToken()

            <div class="card mt-5 border border-warning border-2">
                <div class="card-header bg-primary">
                    <h5 class="card-title text-white">Listado de Usuarios</h5>
                </div>
                <div class="card-body">
                    <table id="tblLista" class="table table-responsive-md table-striped table-hover table-borderless">
                        <thead>
                            <tr class="bg-success text-white">
                                <th>
                                    @Html.DisplayNameFor(model => model.Nombres)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Apellidos)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Correo)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.IdRol)
                                </th>
                                <th>Clasificación</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                int i = 0;

                                <tr>
                                    <td class="text-start">@item.Nombres</td>
                                    <td class="text-start">@item.Apellidos</td>
                                    <td class="text-start">@item.Correo</td>
                                    <td>@Html.DropDownListFor(model => item.IdRol, item.Roles, new { @class = "form-select form-select-sm cmbRol", id = "IdRol", name = "IdRol"})</td>
                                    <td>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <div class="ratings">
                                                @if (@item.punteoBE.estrella1.Equals(1))
                                                {
                                                    <i class="fa fa-star rating-color"></i>
                                                } else
                                                {
                                                    <i class="fa fa-star text-secondary"></i>
                                                }
                                                @if (@item.punteoBE.estrella2.Equals(1))
                                                {
                                                    <i class="fa fa-star rating-color"></i>
                                                }
                                                else
                                                {
                                                    <i class="fa fa-star text-secondary"></i>
                                                }
                                                @if (@item.punteoBE.estrella3.Equals(1))
                                                {
                                                    <i class="fa fa-star rating-color"></i>
                                                }
                                                else
                                                {
                                                    <i class="fa fa-star text-secondary"></i>
                                                }
                                                @if (@item.punteoBE.estrella4.Equals(1))
                                                {
                                                    <i class="fa fa-star rating-color"></i>
                                                }
                                                else
                                                {
                                                    <i class="fa fa-star text-secondary"></i>
                                                }
                                                @if (@item.punteoBE.estrella5.Equals(1))
                                                {
                                                    <i class="fa fa-star rating-color"></i>
                                                }
                                                else
                                                {
                                                    <i class="fa fa-star text-secondary"></i>
                                                }
                                                
                                            </div>
                                            <h5 class="text-success"> @item.punteoBE.Punteo</h5>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="button" value="Cambiar" id="btnGuardar" class="btn btn-sm btn-outline-warning btnSelect" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer bg-warning mt-2">
                    <div class="text-end">
                        <input type="button" class="btn btn-outline-primary" value="Grabar" onclick="ActualizarUsuarios()" />
                    </div>
                </div>
            </div>
        }
    }

</div>