trivia-gt/Controllers/ConfiguracionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;
using trivia_gt.DAL;
using trivia_gt.Models;

namespace trivia_gt.Controllers
{
    public class ConfiguracionController : Controller
    {
        [HttpGet]
        public IActionResult Editar()
        {
            ConfiguracionBE configuracionBE = new ConfiguracionBE();
            ConfiguracionDAL configuracionDAL = new ConfiguracionDAL();

            List<ConfiguracionBE> _lista = new List<ConfiguracionBE>();

            if (HttpContext.Session.GetString("Correo") == null)
            {
                return Redirect("/Login/Login");
            }

            _lista = configuracionDAL.Listar(new ConfiguracionBE());

            if (_lista.Count > 0)
            {
                configuracionBE = _lista[0];
            }

            ViewBag.Nombres = HttpContext.Session.GetString("Nombres");
            ViewBag.IdRol = HttpContext.Session.GetInt32("IdRol");
            ViewBag.Imagen = @"https://drive.google.com/uc?export=view&id=" + HttpContext.Session.GetString("Imagen");
            ViewBag.Visible = false;
            ViewBag.Nivel = 0;
            ViewBag.Percentage = 0;
            ViewBag.ImagenCombo = @"https://drive.google.com/uc?export=view&id=1wQ3L1xIfvyfoUueYKik5GTNTM1tYU89w";

            return View(configuracionBE);
        }

        [HttpPost]
        public IActionResult Editar(ConfiguracionBE entidad)
        {
            ConfiguracionDAL configuracionDAL = new ConfiguracionDAL();

            if (!IsWebsiteUp_Get(entidad.urlApi))
            {
                ViewBag.Nombres = HttpContext.Session.GetString("Nombres");
                ViewBag.IdRol = HttpContext.Session.GetInt32("IdRol");
                ViewBag.Imagen = @"https://drive.google.com/uc?export=view&id=" + HttpContext.Session.GetString("Imagen");
                ViewBag.Visible = false;
                ViewBag.Nivel = 0;
                ViewBag.Percentage = 0;
                ViewBag.ImagenCombo = @"https://drive.google.com/uc?export=view&id=1wQ3L1xIfvyfoUueYKik5GTNTM1tYU89w";

                ModelState.AddModelError("urlApi", "La url ingresada no es valida");

                return View(entidad);

            }

            if (entidad.idConfiguracion == 0)
            {
                configuracionDAL.Crear(entidad);
            }
            else
            {
                configuracionDAL.Actualizar(entidad);
            }

            return Redirect("/Login/Logout");
        }

        private bool IsWebsiteUp_Get(string url)
        {
            url += "1&grupo=1";

            try
            {

                HttpClient httpClient = new HttpClient();
                HttpResponseMessage httpResponse = httpClient.GetAsync(url).Result;
                return httpResponse.IsSuccessStatusCode;
            }
            catch (Exception)
            {

                return false;
            }
        }
    }
}

trivia-gt/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Text;
using trivia_gt.DAL;
using trivia_gt.Models;

namespace trivia_gt.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Login() => View();

        [HttpPost]
        [Produces("application/json")]
        public IActionResult Login(UsuarioBE entidad)
        {
            UsuarioDAL usuarioDAL = new();

            if (entidad.Correo == null)
            {
                return Json(new { success = false, message = "<p class='h5'>El correo es un dato requerido</p>" }, new Newtonsoft.Json.JsonSerializerSettings());
            }

            if (entidad.Clave == null)
            {
                return Json(new { success = false, message = "<p class='h5'>La contraseña es un dato requerido</p>" }, new Newtonsoft.Json.JsonSerializerSettings());
            }

            List<UsuarioBE> listaUsuario = usuarioDAL.Listar(entidad);

            if (listaUsuario.Count == 0)
            {
                return Json(new { success = false, message = "<p class='h5'>El correo ingresado no esta registrado</p>" }, new Newtonsoft.Json.JsonSerializerSettings());
            }

            if (!listaUsuario[0].Clave.Equals(entidad.Clave))
            {
                return Json(new { success = false, message = "<p class='h5'>La clave ingresada es incorrecta</p>" }, new Newtonsoft.Json.JsonSerializerSettings());
            }

            HttpContext.Session.SetInt32("IdUsuario", listaUsuario[0].IdUsuario);
            HttpContext.Session.SetInt32("IdRol", int.Parse(listaUsuario[0].IdRol.ToString()));
            HttpContext.Session.SetString("Nombres", listaUsuario[0].Nombres + " " + listaUsuario[0].Apellidos);
            HttpContext.Session.SetString("Correo", entidad.Correo);
            HttpContext.Session.SetString("Imagen", listaUsuario[0].url);
            HttpContext.Session.SetString("FechaConexion", listaUsuario[0].fechaUltimaConexion);
            HttpContext.Session.SetInt32("DiasConexion", int.Parse(listaUsuario[0].diasUltimaConexion));

            if (HttpContext.Session.GetString("informacion") == null)
            {
                ViewBag.Info = null;
            }
            else
            {
                ViewBag.Info = HttpContext.Session.GetString("informacion");
                HttpContext.Session.Remove("informacion");
            }

            entidad.IsEditing = false;
            usuarioDAL.Actualizar(entidad);

            //carga la url del web services

            ConfiguracionDAL configuracionDAL = new();

            List<ConfiguracionBE> _lista = new List<ConfiguracionBE>();

            _lista = configuracionDAL.Listar(new ConfiguracionBE());

            Utilities.CargaPreguntas(HttpContext.Session, _lista[0].noGrupo, _lista[0].urlApi);

            return Json(new { success = true, direccion = "/Home/Index" }, new Newtonsoft.Json.JsonSerializerSettings());
        }

        [HttpGet]
        public ActionResult Logout()
        {
            HttpContext.Session.Clear();

            return Redirect("/Login/Login");
        }

        private string Mensaje(ModelStateDictionary modelState)
        {
            StringBuilder html = new(string.Empty);

            html.Append("<ul class='text-start'>");

            foreach (var key in modelState.Keys)
            {
                foreach (ModelError error in ModelState[key].Errors)
                {
                    html.Append(@"<li>" + error.ErrorMessage + @"</li>");
                }
            }

            html.Append("</ul>");

            return html.ToString();
        }

    }
}

trivia-gt/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using trivia_gt.DAL;
using trivia_gt.Models;

namespace trivia_gt.Controllers
{
    public class PerfilController : Controller
    {
        [HttpGet]
        public IActionResult Editar()
        {
            UsuarioBE usuarioBE = new UsuarioBE();
            PerfilDAL perfilDAL = new PerfilDAL();

            List<UsuarioBE> _lista = new List<UsuarioBE>();

            if (HttpContext.Session.GetString("Correo") == null)
            {
                return Redirect("/Login/Login");
            }

            usuarioBE.Correo = HttpContext.Session.GetString("Correo");
            
            
            _lista = perfilDAL.Listar(usuarioBE);

            usuarioBE = _lista[0];
            usuarioBE.ListaAvatar = new List<AvatarBE>();
            usuarioBE.ListaAvatar.AddRange(CargarAvatar());

            usuarioBE.Roles = new List<SelectListItem>();
            usuarioBE.Roles.Add(new SelectListItem { Value = "1", Text = "Jugador" });
            usuarioBE.Roles.Add(new SelectListItem { Value = "2", Text = "Administrador" });


            ViewBag.Nombres = HttpContext.Session.GetString("Nombres");
            ViewBag.Imagen = @"https://drive.google.com/uc?export=view&id=" + HttpContext.Session.GetString("Imagen");
            ViewBag.Visible = false;
            ViewBag.Nivel = 0;
            ViewBag.Percentage = 0;
            ViewBag.ImagenCombo = @"https://drive.google.com/uc?export=view&id=1wQ3L1xIfvyfoUueYKik5GTNTM1tYU89w";
            ViewBag.IdRol = HttpContext.Session.GetInt32("IdRol");

            return View(usuarioBE);
        }

        [HttpPost]
        public IActionResult Editar(UsuarioBE entidad)
        {
            PerfilDAL perfilDAL = new();
            UsuarioBE usuarioBE = new();
            UsuarioDAL usuarioDAL = new();

            List<UsuarioBE> _lista = new List<UsuarioBE>();

            usuarioBE.Correo = HttpContext.Session.GetString("Correo");
            entidad.Correo = usuarioBE.Correo;

            if (entidad.IdRol == null)
            {
                entidad.IdRol = 1;
            }

            DateTime fechaNacimiento = Convert.ToDateTime(entidad.FechaNacimiento);
            DateTime startDate = new DateTime(1921, 1, 1, 0, 0, 0);

            if (fechaNacimiento < startDate || fechaNacimiento > DateTime.Now)
            {
                ViewBag.Nombres = HttpContext.Session.GetString("Nombres");
                ViewBag.Imagen = @"https://drive.google.com/uc?export=view&id=" + HttpContext.Session.GetString("Imagen");
                ViewBag.Visible = false;
                ViewBag.Nivel = 0;
                ViewBag.Percentage = 0;
                ViewBag.ImagenCombo = @"https://drive.google.com/uc?export=view&id=1wQ3L1xIfvyfoUueYKik5GTNTM1tYU89w";

                entidad.ListaAvatar = CargarAvatar();
                entidad.Roles = new List<SelectListItem>();
                entidad.Roles.Add(new SelectListItem { Value = "1", Text = "Jugador", Selected = true });
                entidad.Roles.Add(new SelectListItem { Value = "2", Text = "Administrador" });

                ModelState.AddModelError("FechaNacimiento", "La fecha de nacimiento no puede ser menor a 01/01/1921 ni mayor a hoy");
                ModelState.Remove("IdRol");
                ModelState.Remove("Correo");

                return View(entidad);
            }

            _ = perfilDAL.Actualizar(entidad);
            _lista = usuarioDAL.Listar(usuarioBE);

            HttpContext.Session.Remove("Imagen");
            HttpContext.Session.Remove("Nombres");
            HttpContext.Session.SetString("Imagen", _lista[0].url);
            HttpContext.Session.SetString("Nombres", _lista[0].Nombres + " " + _lista[0].Apellidos);
            HttpContext.Session.SetString("informacion", "Registro Actualizado");

            return Redirect("/Home/Index");

        }

        [HttpGet]
        public IActionResult Crear()
        {
            UsuarioBE usuarioBE = new UsuarioBE();
            PerfilDAL perfilDAL = new PerfilDAL();

            usuarioBE.Correo = HttpContext.Session.GetString("Correo");

            List<UsuarioBE> _lista = perfilDAL.Listar(usuarioBE);

            usuarioBE.ListaAvatar = CargarAvatar();
            usuarioBE.Roles = new List<SelectListItem>();
            usuarioBE.Roles.Add(new SelectListItem { Value = "1", Text = "Jugador", Selected = true });
            usuarioBE.Roles.Add(new SelectListItem { Value = "2", Text = "Administrador" });
            usuarioBE.IdRol = 1;

            

            return View(usuarioBE);
        }

        [HttpPost]
        public IActionResult Crear(UsuarioBE entidad)
        {
            
            PerfilDAL perfilDAL = new();

            entidad.IdRol = 1;

            DateTime fechaNacimiento = Convert.ToDateTime(entidad.FechaNacimiento);
            DateTime startDate = new DateTime(1921, 1, 1, 0, 0, 0);

            if (fechaNacimiento < startDate || fechaNacimiento > DateTime.Now)
            {
                entidad.ListaAvatar = CargarAvatar();
                entidad.Roles = new List<SelectListItem>();
                entidad.Roles.Add(new SelectListItem { Value = "1", Text = "Jugador", Selected = true });
                entidad.Roles.Add(new SelectListItem { Value = "2", Text = "Administrador" });

                ModelState.AddModelError("FechaNacimiento", "La fecha de nacimiento no puede ser menor a 01/01/1921 ni mayor a hoy");
                ModelState.Remove("IdRol");

                return View(entidad);
            }


            if (CorreoYaRegistrado(entidad.Correo))
            {

                entidad.ListaAvatar = CargarAvatar();
                entidad.Roles = new List<SelectListItem>();
                entidad.Roles.Add(new SelectListItem { Value = "1", Text = "Jugador" , Selected = true });
                entidad.Roles.Add(new SelectListItem { Value = "2", Text = "Administrador"});

                ModelState.AddModelError("Correo", "El correo ingresado ya esta registrado");
                ModelState.Remove("IdRol");

                return View(entidad);
            }

            
            
            _ = perfilDAL.Crear(entidad);

            HttpContext.Session.SetString("informacion", "Registro creado");

            return Redirect("/Login/Login");

        }

        private List<AvatarBE> CargarAvatar()
        {
            AvatarDAL avatarDAL = new AvatarDAL();

            List<AvatarBE> _listaAvatar = avatarDAL.Listar(new AvatarBE());

            return _listaAvatar;

        }

        private bool CorreoYaRegistrado(string correo)
        {
            UsuarioBE usuarioBE = new UsuarioBE();
            PerfilDAL perfilDAL = new PerfilDAL();

            List<UsuarioBE> _lista = new List<UsuarioBE>();

            usuarioBE.Correo = correo;

            _lista = perfilDAL.Listar(usuarioBE);

            if (_lista.Any())
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

trivia-gt/Views/Shared/_Layout.cshtml
@{
    string nombres = ViewBag.Nombres;
    string image = ViewBag.Imagen;
    bool mostrar = ViewBag.Visible;
    int nivel = ViewBag.Nivel;
    int porcentaje = ViewBag.Percentage;
    string mensaje = ViewBag.mensaje;
    int IdRol = ViewBag.IdRol;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Trivia Guatemala</title>
    <link rel="icon" type="image/x-icon" href="~/images/guate.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/notify/notiflix-3.2.5.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/dd.css" asp-append-version="true" />
</head>
<body style="background-image:url(/images/gt_simbolos.jpg)" onload="ShowMensajeInformacion()">


    <input type=hidden id="iInfo" name="iInfo"
           value="@ViewBag.Info" />

    <div class="jumbotron-fluid">
        <div class="container-fluid ">
            <div class="row flex-nowrap">
                <div class="col-auto px-0">
                    <div id="sidebar" class="collapse collapse-horizontal show border-end">
                        <div class="sidebar-heading border-bottom bg-warning">
                            <div class="card align-content-center text-center bg-warning">
                                <img class="w-50 h-auto rounded card-img-top mx-auto d-block" src="@image">
                                <div class="card-body">
                                    <p class="card-text text-success font-weight-bold">@nombres</p>
                                </div>
                            </div>
                        </div>
                        <div id="sidebar-nav" class="list-group border-0 rounded-0 text-sm-start bg-warning min-vh-100">
                            <a href="@Url.Action("Editar","Perfil")" class="list-group-item list-group-item-action list-group-item-primary p-3 border-end-0 d-inline-block text-truncate config" data-bs-parent="#sidebar"><i class="fa-solid fa-user"></i> <span>Mi Perfil</span> </a>
                            <a href="@Url.Action("Construccion", "Home")" class="list-group-item list-group-item-action list-group-item-primary p-3 border-end-0 d-inline-block text-truncate config" data-bs-parent="#sidebar"><i class="fa-solid fa-users"></i> <span>Mis Amigos</span></a>
                            @if(IdRol == 2){
                                <a href="@Url.Action("Editar", "Configuracion")" class="list-group-item list-group-item-action list-group-item-primary p-3 border-end-0 d-inline-block text-truncate config" data-bs-parent="#sidebar"><i class="fa-solid fa-gears"></i> <span>Configuración</span></a>
                            }
                            <a href="@Url.Action("Logout", "Login")" class="list-group-item list-group-item-action list-group-item-primary p-3 border-end-0 d-inline-block text-truncate config" data-bs-parent="#sidebar"><i class="fa-solid fa-right-from-bracket"></i> <span>Cerrar Session</span></a>
                        </div>
                    </div>
                </div>
                <div class="col p-0 m-0">

                    <nav class="navbar navbar-expand-lg navbar-light bg-warning border-bottom">
                        <div class="container-fluid">
                            <button class="btn btn-primary" id="sidebarToggle" data-bs-target="#sidebar" data-bs-toggle="collapse">
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            @if (ViewBag.Visible)
                            {
                                <span class="navbar-text font-weight-bold" style="font-size:large!important">
                                    Nivel <span class="badge bg-success" style="font-size:large!important">@nivel</span>
                                </span>

                                <div class="progress" style="width: 25em; height: 20px;">
                                    <!-- 25em = half the screen width -->
                                    <div class="progress-bar" style="width:@porcentaje%">@porcentaje%</div>
                                </div>
                            }

                            @if (ViewBag.mensaje != null)
                            {
                                <span class="navbar-text font-weight-bold" style="font-size:large!important">
                                    @mensaje
                                </span>
                            }

                        </div>

                    </nav>

                    <div class="container-fluid">
                        <div class="row d-flex">
                            <div class="col-12">
                                <div class="align-items-center justify-content-center">
                                    <main role="main">
                                        @RenderBody()
                                    </main>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/js/notify/notiflix-notify-aio-3.2.5.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/usuarios.js" asp-append-version="true"></script>
    <script src="~/js/dd.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>